# data preprocessing args
preprocess_data: False
run_name: 'gazebo_sim1'
rosbag_filepath: './sim_state_control_data_run_1.bag'
topics: ["/ground_truth/state_transformed", "/chassisState"]
make_preprocessing_plots: True

# model training args
train_model: True
results_dir: './models/'
device: 'cuda:0'
epochs: 1
batch_size: 128
lr: 0.01
training_data_path: ''
test_data_path: ''
state_dim: 7
nn_layers: [6, 32, 32, 4]
time_horizon: 3